"""Offline dataset D_logs (Spec Section 9).

Generated by a mixed behavior policy: ~60% greedy_nearest, ~40% noisy/eps-random.
Stored as a compressed .npz with d4rl-style arrays. Coverage gaps are intentional
(the eps-random component never explores some greedy regions and vice-versa).
"""
from __future__ import annotations

from typing import Optional
import numpy as np

from .config import Config
from .env_dispatch import DroneDispatchEnv
from .baselines import GreedyNearest, RandomPolicy


def _flatten_obs(obs):
    """Flatten the Dict observation to a fixed-length vector (drones+orders+time)."""
    return np.concatenate([
        obs["drones"].flatten(),
        obs["orders"].flatten(),
        obs["time"].astype(np.float32),
    ]).astype(np.float32)


class _MixedBehavior:
    def __init__(self, cfg, seed, greedy_frac=0.6, eps=0.3):
        self.cfg = cfg
        self.greedy = GreedyNearest(cfg)
        self.rng = np.random.default_rng(seed)
        self.greedy_frac = greedy_frac
        self.eps = eps

    def act(self, obs):
        mask = np.asarray(obs["action_mask"])
        valid = np.flatnonzero(mask)
        if self.rng.random() < self.greedy_frac:
            a = self.greedy.act(obs)
            if self.rng.random() < self.eps:  # noise on the greedy branch
                a = int(self.rng.choice(valid))
            return a
        return int(self.rng.choice(valid))


def generate_offline_dataset(path: str, config: Optional[Config] = None,
                             min_transitions: int = 200_000, base_seed: int = 1000):
    cfg = config or Config()
    env = DroneDispatchEnv(cfg)
    obs_l, act_l, rew_l, nobs_l, term_l, tout_l, ep_ret = [], [], [], [], [], [], []
    seed = base_seed
    while len(act_l) < min_transitions:
        policy = _MixedBehavior(cfg, seed)
        obs, _ = env.reset(seed=seed)
        done, ret = False, 0.0
        while not done:
            a = policy.act(obs)
            nobs, r, term, trunc, _ = env.step(a)
            obs_l.append(_flatten_obs(obs))
            act_l.append(a)
            rew_l.append(r)
            nobs_l.append(_flatten_obs(nobs))
            term_l.append(term)
            tout_l.append(trunc)
            ret += r
            obs = nobs
            done = term or trunc
        ep_ret.append(ret)
        seed += 1

    np.savez_compressed(
        path,
        observations=np.asarray(obs_l, dtype=np.float32),
        actions=np.asarray(act_l, dtype=np.int64),
        rewards=np.asarray(rew_l, dtype=np.float32),
        next_observations=np.asarray(nobs_l, dtype=np.float32),
        terminals=np.asarray(term_l, dtype=bool),
        timeouts=np.asarray(tout_l, dtype=bool),
        episode_returns=np.asarray(ep_ret, dtype=np.float32),
    )
    return path


def load_offline_dataset(path: str) -> dict:
    d = np.load(path)
    return {k: d[k] for k in d.files}


def make_preference_pairs(path: str, n_pairs: int = 1000, seed: int = 0):
    """Yield trajectory-segment pairs labeled by return: (seg_a, seg_b, label),
    label=1 if seg_a has the higher summed reward, else 0. Segments are fixed
    windows of transitions."""
    data = load_offline_dataset(path)
    rng = np.random.default_rng(seed)
    rewards = data["rewards"]
    # episode ends at a true terminal OR a timeout (truncation); falls back to
    # terminals-only for older datasets without a timeouts array.
    boundary = data["terminals"].copy()
    if "timeouts" in data:
        boundary = boundary | data["timeouts"]
    n = len(rewards)
    seg_len = 25

    ends = list(np.flatnonzero(boundary)) + [n - 1]
    starts = [0] + [e + 1 for e in ends[:-1]]
    episodes = [(s, e) for s, e in zip(starts, ends) if e - s >= seg_len]
    if not episodes:
        raise ValueError("no episode is long enough for a segment of length "
                         f"{seg_len}")

    pairs = []
    for _ in range(n_pairs):
        (sa, ea), (sb, eb) = (episodes[rng.integers(len(episodes))],
                              episodes[rng.integers(len(episodes))])
        ia = rng.integers(sa, ea - seg_len + 1)
        ib = rng.integers(sb, eb - seg_len + 1)
        seg_a = slice(ia, ia + seg_len)
        seg_b = slice(ib, ib + seg_len)
        ra, rb = rewards[seg_a].sum(), rewards[seg_b].sum()
        label = 1 if ra >= rb else 0
        pairs.append({
            "obs_a": data["observations"][seg_a],
            "act_a": data["actions"][seg_a],
            "obs_b": data["observations"][seg_b],
            "act_b": data["actions"][seg_b],
            "label": label,
        })
    return pairs
